// Re-export Prisma enums for use throughout the app
import {
  Role,
  PlayerStatus,
  VillageStatus,
  Winner,
  RoomType,
  PostOwner,
  UserRole,
} from "@prisma/client";

export {
  Role,
  PlayerStatus,
  VillageStatus,
  Winner,
  RoomType,
  PostOwner,
  UserRole,
};

// Role composition by player count (from jinro_rails/config/settings.yml)
export const ROLE_COMPOSITIONS: Record<number, Role[]> = {
  5: ["VILLAGER", "VILLAGER", "VILLAGER", "WEREWOLF", "FORTUNE_TELLER"],
  6: [
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "WEREWOLF",
    "FORTUNE_TELLER",
  ],
  7: [
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "WEREWOLF",
    "FORTUNE_TELLER",
    "MADMAN",
  ],
  8: [
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "WEREWOLF",
    "WEREWOLF",
    "FORTUNE_TELLER",
    "BODYGUARD",
    "MADMAN",
  ],
  9: [
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "WEREWOLF",
    "WEREWOLF",
    "FORTUNE_TELLER",
    "BODYGUARD",
    "MADMAN",
  ],
  10: [
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "WEREWOLF",
    "WEREWOLF",
    "FORTUNE_TELLER",
    "PSYCHIC",
    "BODYGUARD",
    "MADMAN",
  ],
  11: [
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "WEREWOLF",
    "WEREWOLF",
    "FORTUNE_TELLER",
    "PSYCHIC",
    "BODYGUARD",
    "MADMAN",
  ],
  12: [
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "WEREWOLF",
    "WEREWOLF",
    "FORTUNE_TELLER",
    "PSYCHIC",
    "BODYGUARD",
    "MADMAN",
  ],
  13: [
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "WEREWOLF",
    "WEREWOLF",
    "WEREWOLF",
    "FORTUNE_TELLER",
    "PSYCHIC",
    "BODYGUARD",
    "MADMAN",
  ],
  14: [
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "WEREWOLF",
    "WEREWOLF",
    "WEREWOLF",
    "FORTUNE_TELLER",
    "PSYCHIC",
    "BODYGUARD",
    "MADMAN",
  ],
  15: [
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "WEREWOLF",
    "WEREWOLF",
    "WEREWOLF",
    "FORTUNE_TELLER",
    "PSYCHIC",
    "BODYGUARD",
    "MADMAN",
  ],
  16: [
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "VILLAGER",
    "WEREWOLF",
    "WEREWOLF",
    "WEREWOLF",
    "FORTUNE_TELLER",
    "PSYCHIC",
    "BODYGUARD",
    "MADMAN",
  ],
} as const;

// Role display names (Japanese)
export const ROLE_DISPLAY_NAMES: Record<string, string> = {
  VILLAGER: "村人",
  WEREWOLF: "人狼",
  FORTUNE_TELLER: "占い師",
  PSYCHIC: "霊媒師",
  BODYGUARD: "騎士",
  MADMAN: "狂人",
};

// Role team classification
export type Team = "HUMAN" | "WEREWOLF";

export const ROLE_TEAMS: Record<string, Team> = {
  VILLAGER: "HUMAN",
  WEREWOLF: "WEREWOLF",
  FORTUNE_TELLER: "HUMAN",
  PSYCHIC: "HUMAN",
  BODYGUARD: "HUMAN",
  MADMAN: "WEREWOLF", // Madman wins with werewolves
};
